version: "3.8"

services:
  d-registry:
    image: registry:2
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.d-registry == true
    ports:
      - "5000:5000"
    volumes:
      - /mnt/registry-data:/var/lib/registry
  express-server:
    build: .
    restart: unless-stopped
    ports:
      - "${EXPRESS_PORT}:${EXPRESS_PORT}" # Use the variable from .env
    env_file:
      - ./.env # Load environment variables from .env file

# docker service d-registry 관련
# docker service create \
#   --name d-registry \
#   --publish 5000:5000 \
#   --replicas 1 \
#   --constraint 'node.labels.d-registry == true' \
#   --mount type=bind,source=/mnt/registry-data,target=/var/lib/registry \
#   registry:2
