-- ============================================================
-- Oracle 타임존 마이그레이션 스크립트
-- 실행 환경: DBeaver (Auto-Commit OFF 권장)
-- 작성일: 2026-04-10
-- ============================================================
--
-- 작업 순서:
--   STEP 1: 백업 테이블 생성 (DDL → 자동 커밋, 안전)
--   STEP 2: startAt/endAt 데이터 보정 (DML → SELECT 확인 후 COMMIT)
--   STEP 3: 7개 컬럼 타입 변경 (DDL → 자동 커밋, 백업이 보험)
--   STEP 4: 최종 검증
--   STEP 5: 백업 정리 (선택사항)
--
-- 주의사항:
--   - DDL (ALTER TABLE, CREATE TABLE)은 Oracle에서 자동 COMMIT됩니다
--   - DML (UPDATE)은 COMMIT 전까지 ROLLBACK 가능합니다
--   - 각 STEP 사이에 검증 쿼리를 실행해서 결과를 눈으로 확인하세요
--   - 상용 적용 시 서비스 중단 없이 가능하나, 트래픽 적은 시간 권장
-- ============================================================


-- ============================================================
-- STEP 1: 백업 테이블 생성
-- (DDL → 자동 커밋됨. 원본 데이터에 영향 없음)
-- ============================================================

CREATE TABLE TEAM_TASKS_BACKUP AS SELECT * FROM TEAM_TASKS;
CREATE TABLE TASK_COMMENTS_BACKUP AS SELECT * FROM TASK_COMMENTS;
CREATE TABLE TEAM_INVITATIONS_BACKUP AS SELECT * FROM TEAM_INVITATIONS;
CREATE TABLE TEAM_TELEGRAM_LINKS_BACKUP AS SELECT * FROM TEAM_TELEGRAM_LINKS;

-- 백업 확인
SELECT 'TEAM_TASKS' as TBL, COUNT(*) as CNT FROM TEAM_TASKS_BACKUP
UNION ALL SELECT 'TASK_COMMENTS', COUNT(*) FROM TASK_COMMENTS_BACKUP
UNION ALL SELECT 'TEAM_INVITATIONS', COUNT(*) FROM TEAM_INVITATIONS_BACKUP
UNION ALL SELECT 'TEAM_TELEGRAM_LINKS', COUNT(*) FROM TEAM_TELEGRAM_LINKS_BACKUP;


-- ============================================================
-- STEP 2: startAt/endAt 데이터 보정
-- (DML → ROLLBACK 가능. SELECT로 확인 후 COMMIT)
--
-- 원인: buildTaskDatetime이 Z suffix를 붙여 전송
--       → 사용자 KST 입력값이 UTC로 잘못 저장됨
-- 대상: +00:00 offset 데이터만 (46건 START_AT, 53건 END_AT)
-- 처리: -9시간 보정
-- ============================================================

-- [2-1] 보정 전 현재 상태 확인 (task 601, 602로 검증)
SELECT TASK_ID,
       TO_CHAR(START_AT, 'YYYY-MM-DD HH24:MI:SS TZH:TZM') as START_AT_BEFORE,
       TO_CHAR(END_AT, 'YYYY-MM-DD HH24:MI:SS TZH:TZM') as END_AT_BEFORE
FROM TEAM_TASKS
WHERE TASK_ID IN (601, 602)
ORDER BY TASK_ID;
-- 예상:
--   601: START_AT = 2026-04-10 00:10:00 +09:00 (변경 안 될 것)
--   602: START_AT = 2026-04-09 16:54:00 +00:00 (→ 07:54:00 +00:00으로 변경될 것)

-- [2-2] START_AT 보정 실행
UPDATE TEAM_TASKS SET START_AT = START_AT - INTERVAL '9' HOUR
WHERE START_AT IS NOT NULL AND EXTRACT(TIMEZONE_HOUR FROM START_AT) = 0;

-- [2-3] END_AT 보정 실행
UPDATE TEAM_TASKS SET END_AT = END_AT - INTERVAL '9' HOUR
WHERE END_AT IS NOT NULL AND EXTRACT(TIMEZONE_HOUR FROM END_AT) = 0;

-- [2-4] 보정 후 결과 확인 ★★★ 여기서 반드시 확인 ★★★
SELECT TASK_ID,
       TO_CHAR(START_AT, 'YYYY-MM-DD HH24:MI:SS TZH:TZM') as START_AT_AFTER,
       TO_CHAR(END_AT, 'YYYY-MM-DD HH24:MI:SS TZH:TZM') as END_AT_AFTER
FROM TEAM_TASKS
WHERE TASK_ID IN (601, 602)
ORDER BY TASK_ID;
-- 예상 결과:
--   601: START_AT = 2026-04-10 00:10:00 +09:00 (변경 없음 ✓)
--   602: START_AT = 2026-04-09 07:54:00 +00:00 (KST 16:54 = UTC 07:54 ✓)

-- [2-5] 전체 건수 확인
SELECT 'START_AT 보정' as ITEM,
       (SELECT COUNT(*) FROM TEAM_TASKS WHERE START_AT IS NOT NULL) as TOTAL,
       (SELECT COUNT(*) FROM TEAM_TASKS WHERE START_AT IS NOT NULL AND EXTRACT(TIMEZONE_HOUR FROM START_AT) = 0) as PLUS_00,
       (SELECT COUNT(*) FROM TEAM_TASKS WHERE START_AT IS NOT NULL AND EXTRACT(TIMEZONE_HOUR FROM START_AT) = 9) as PLUS_09
FROM DUAL
UNION ALL
SELECT 'END_AT 보정',
       (SELECT COUNT(*) FROM TEAM_TASKS WHERE END_AT IS NOT NULL),
       (SELECT COUNT(*) FROM TEAM_TASKS WHERE END_AT IS NOT NULL AND EXTRACT(TIMEZONE_HOUR FROM END_AT) = 0),
       (SELECT COUNT(*) FROM TEAM_TASKS WHERE END_AT IS NOT NULL AND EXTRACT(TIMEZONE_HOUR FROM END_AT) = 9)
FROM DUAL;

-- ★★★ 결과가 정상이면 아래 COMMIT 실행 ★★★
-- ★★★ 결과가 이상하면 ROLLBACK 실행 ★★★
COMMIT;
-- ROLLBACK;


-- ============================================================
-- STEP 3: 컬럼 타입 변경 (7개)
-- (DDL → 자동 커밋됨. ROLLBACK 불가. 백업이 보험)
--
-- 방식: 새 컬럼 추가 → 데이터 복사 → 기존 컬럼 삭제 → 이름 변경
-- 기존 데이터: 상용 대부분 UTC → FROM_TZ(col, 'UTC')로 변환
-- ============================================================

-- --------------------------------------------------------
-- [3-1] TASK_COMMENTS.CRTD_AT (NOT NULL, DEFAULT CURRENT_TIMESTAMP)
-- --------------------------------------------------------
ALTER TABLE TASK_COMMENTS ADD (CRTD_AT_NEW TIMESTAMP(6) WITH TIME ZONE);

UPDATE TASK_COMMENTS SET CRTD_AT_NEW = FROM_TZ(CRTD_AT, 'UTC') WHERE CRTD_AT IS NOT NULL;
COMMIT;

ALTER TABLE TASK_COMMENTS DROP COLUMN CRTD_AT;
ALTER TABLE TASK_COMMENTS RENAME COLUMN CRTD_AT_NEW TO CRTD_AT;
ALTER TABLE TASK_COMMENTS MODIFY (CRTD_AT DEFAULT CURRENT_TIMESTAMP NOT NULL);

-- 확인
SELECT COMMENT_ID, TO_CHAR(CRTD_AT, 'YYYY-MM-DD HH24:MI:SS TZH:TZM') as CRTD_AT
FROM TASK_COMMENTS ORDER BY COMMENT_ID DESC FETCH FIRST 3 ROWS ONLY;

-- --------------------------------------------------------
-- [3-2] TASK_COMMENTS.MDFD_AT (nullable)
-- --------------------------------------------------------
ALTER TABLE TASK_COMMENTS ADD (MDFD_AT_NEW TIMESTAMP(6) WITH TIME ZONE);

UPDATE TASK_COMMENTS SET MDFD_AT_NEW = FROM_TZ(MDFD_AT, 'UTC') WHERE MDFD_AT IS NOT NULL;
COMMIT;

ALTER TABLE TASK_COMMENTS DROP COLUMN MDFD_AT;
ALTER TABLE TASK_COMMENTS RENAME COLUMN MDFD_AT_NEW TO MDFD_AT;

-- 확인
SELECT COMMENT_ID, TO_CHAR(MDFD_AT, 'YYYY-MM-DD HH24:MI:SS TZH:TZM') as MDFD_AT
FROM TASK_COMMENTS WHERE MDFD_AT IS NOT NULL FETCH FIRST 3 ROWS ONLY;

-- --------------------------------------------------------
-- [3-3] TEAM_INVITATIONS.END_AT (NOT NULL)
-- --------------------------------------------------------
ALTER TABLE TEAM_INVITATIONS ADD (END_AT_NEW TIMESTAMP(6) WITH TIME ZONE);

UPDATE TEAM_INVITATIONS SET END_AT_NEW = FROM_TZ(END_AT, 'UTC') WHERE END_AT IS NOT NULL;
COMMIT;

ALTER TABLE TEAM_INVITATIONS DROP COLUMN END_AT;
ALTER TABLE TEAM_INVITATIONS RENAME COLUMN END_AT_NEW TO END_AT;
ALTER TABLE TEAM_INVITATIONS MODIFY (END_AT NOT NULL);

-- 확인
SELECT INVITE_ID, TO_CHAR(END_AT, 'YYYY-MM-DD HH24:MI:SS TZH:TZM') as END_AT
FROM TEAM_INVITATIONS ORDER BY INVITE_ID DESC FETCH FIRST 3 ROWS ONLY;

-- --------------------------------------------------------
-- [3-4] TEAM_TASKS.COMPLETED_AT (nullable)
-- --------------------------------------------------------
ALTER TABLE TEAM_TASKS ADD (COMPLETED_AT_NEW TIMESTAMP(6) WITH TIME ZONE);

UPDATE TEAM_TASKS SET COMPLETED_AT_NEW = FROM_TZ(COMPLETED_AT, 'UTC') WHERE COMPLETED_AT IS NOT NULL;
COMMIT;

ALTER TABLE TEAM_TASKS DROP COLUMN COMPLETED_AT;
ALTER TABLE TEAM_TASKS RENAME COLUMN COMPLETED_AT_NEW TO COMPLETED_AT;

-- 확인
SELECT TASK_ID, TO_CHAR(COMPLETED_AT, 'YYYY-MM-DD HH24:MI:SS TZH:TZM') as COMPLETED_AT
FROM TEAM_TASKS WHERE COMPLETED_AT IS NOT NULL FETCH FIRST 3 ROWS ONLY;

-- --------------------------------------------------------
-- [3-5] TEAM_TELEGRAM_LINKS.CRTD_AT (NOT NULL, DEFAULT CURRENT_TIMESTAMP)
-- --------------------------------------------------------
ALTER TABLE TEAM_TELEGRAM_LINKS ADD (CRTD_AT_NEW TIMESTAMP(6) WITH TIME ZONE);

UPDATE TEAM_TELEGRAM_LINKS SET CRTD_AT_NEW = FROM_TZ(CRTD_AT, 'UTC') WHERE CRTD_AT IS NOT NULL;
COMMIT;

ALTER TABLE TEAM_TELEGRAM_LINKS DROP COLUMN CRTD_AT;
ALTER TABLE TEAM_TELEGRAM_LINKS RENAME COLUMN CRTD_AT_NEW TO CRTD_AT;
ALTER TABLE TEAM_TELEGRAM_LINKS MODIFY (CRTD_AT DEFAULT CURRENT_TIMESTAMP NOT NULL);

-- --------------------------------------------------------
-- [3-6] TEAM_TELEGRAM_LINKS.END_AT (NOT NULL)
-- --------------------------------------------------------
ALTER TABLE TEAM_TELEGRAM_LINKS ADD (END_AT_NEW TIMESTAMP(6) WITH TIME ZONE);

UPDATE TEAM_TELEGRAM_LINKS SET END_AT_NEW = FROM_TZ(END_AT, 'UTC') WHERE END_AT IS NOT NULL;
COMMIT;

ALTER TABLE TEAM_TELEGRAM_LINKS DROP COLUMN END_AT;
ALTER TABLE TEAM_TELEGRAM_LINKS RENAME COLUMN END_AT_NEW TO END_AT;
ALTER TABLE TEAM_TELEGRAM_LINKS MODIFY (END_AT NOT NULL);

-- --------------------------------------------------------
-- [3-7] TEAM_TELEGRAM_LINKS.USED_AT (nullable)
-- --------------------------------------------------------
ALTER TABLE TEAM_TELEGRAM_LINKS ADD (USED_AT_NEW TIMESTAMP(6) WITH TIME ZONE);

UPDATE TEAM_TELEGRAM_LINKS SET USED_AT_NEW = FROM_TZ(USED_AT, 'UTC') WHERE USED_AT IS NOT NULL;
COMMIT;

ALTER TABLE TEAM_TELEGRAM_LINKS DROP COLUMN USED_AT;
ALTER TABLE TEAM_TELEGRAM_LINKS RENAME COLUMN USED_AT_NEW TO USED_AT;


-- ============================================================
-- STEP 4: 최종 검증
-- ============================================================

-- [4-1] 모든 TIMESTAMP 컬럼 타입 확인 → 전부 WITH TIME ZONE이어야 함
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM USER_TAB_COLUMNS
WHERE DATA_TYPE LIKE 'TIMESTAMP%'
ORDER BY TABLE_NAME, COLUMN_NAME;
-- 예상: 14개 전부 "TIMESTAMP(6) WITH TIME ZONE"

-- [4-2] 데이터 정합성 확인 — 백업과 비교
-- TASK_COMMENTS: 건수 동일한지
SELECT
  (SELECT COUNT(*) FROM TASK_COMMENTS) as CURRENT_CNT,
  (SELECT COUNT(*) FROM TASK_COMMENTS_BACKUP) as BACKUP_CNT
FROM DUAL;

-- TEAM_TASKS: 건수 동일한지
SELECT
  (SELECT COUNT(*) FROM TEAM_TASKS) as CURRENT_CNT,
  (SELECT COUNT(*) FROM TEAM_TASKS_BACKUP) as BACKUP_CNT
FROM DUAL;

-- [4-3] startAt/endAt 보정 결과 최종 확인
SELECT TASK_ID,
       TO_CHAR(START_AT, 'YYYY-MM-DD HH24:MI:SS TZH:TZM') as START_AT,
       TO_CHAR(END_AT, 'YYYY-MM-DD HH24:MI:SS TZH:TZM') as END_AT
FROM TEAM_TASKS
WHERE TASK_ID IN (601, 602)
ORDER BY TASK_ID;
-- 601: START_AT = +09:00 (변경 없음)
-- 602: START_AT = 07:54 +00:00 (보정 완료)

-- [4-4] offset 분포 최종 확인
SELECT * FROM (
  SELECT 'TEAM_TASKS.START_AT' as COL, EXTRACT(TIMEZONE_HOUR FROM START_AT) as TZ, COUNT(*) as CNT
  FROM TEAM_TASKS WHERE START_AT IS NOT NULL GROUP BY EXTRACT(TIMEZONE_HOUR FROM START_AT)
  UNION ALL
  SELECT 'TEAM_TASKS.END_AT', EXTRACT(TIMEZONE_HOUR FROM END_AT), COUNT(*)
  FROM TEAM_TASKS WHERE END_AT IS NOT NULL GROUP BY EXTRACT(TIMEZONE_HOUR FROM END_AT)
  UNION ALL
  SELECT 'TASK_COMMENTS.CRTD_AT', EXTRACT(TIMEZONE_HOUR FROM CRTD_AT), COUNT(*)
  FROM TASK_COMMENTS GROUP BY EXTRACT(TIMEZONE_HOUR FROM CRTD_AT)
) ORDER BY 1, 2;


-- ============================================================
-- STEP 5: 백업 정리 (선택사항)
-- 모든 검증이 완료된 후, 문제 없으면 실행
-- 급하지 않으면 며칠 후 삭제해도 됩니다
-- ============================================================

-- DROP TABLE TEAM_TASKS_BACKUP;
-- DROP TABLE TASK_COMMENTS_BACKUP;
-- DROP TABLE TEAM_INVITATIONS_BACKUP;
-- DROP TABLE TEAM_TELEGRAM_LINKS_BACKUP;
