export * from './api-response.dto';

// 에러 코드 타입 (프론트엔드와 공유용)
export type ErrorCode =
  // 공통 에러
  | 'VALIDATION_ERROR'
  | 'NOT_FOUND'
  | 'FORBIDDEN'
  | 'UNAUTHORIZED'
  | 'BAD_REQUEST'
  | 'INTERNAL_SERVER_ERROR'
  | 'BAD_GATEWAY'
  // Auth 에러
  | 'AUTH_UNAUTHORIZED'
  | 'AUTH_INVALID_TOKEN'
  | 'AUTH_KAKAO_API_ERROR'
  // Team 에러
  | 'TEAM_NOT_FOUND'
  | 'TEAM_FORBIDDEN'
  | 'TEAM_TASK_NOT_FOUND'
  | 'TEAM_TASK_BAD_REQUEST'
  | 'TEAM_COMMENT_NOT_FOUND'
  | 'TEAM_COMMENT_FORBIDDEN'
  | 'TEAM_INVITE_NOT_FOUND'
  | 'TEAM_INVITE_EXPIRED'
  | 'TEAM_INVITE_FORBIDDEN'
  | 'TEAM_MEMBER_ALREADY_EXISTS'
  // Notification 에러
  | 'NOTIFICATION_TELEGRAM_CONFIG_ERROR'
  | 'NOTIFICATION_TELEGRAM_API_ERROR'
  | 'NOTIFICATION_TELEGRAM_LINK_INVALID'
  | 'NOTIFICATION_TELEGRAM_ALREADY_LINKED';
