export * from './api-response.dto';

// 에러 코드 타입 (프론트엔드와 공유용)
// 주의: 새 에러 DTO 추가 시 이 유니온도 함께 갱신할 것 (2026-07-22 실코드 전수 동기화)
export type ErrorCode =
  // 공통 에러
  | 'VALIDATION_ERROR'
  | 'NOT_FOUND'
  | 'FORBIDDEN'
  | 'UNAUTHORIZED'
  | 'BAD_REQUEST'
  | 'CONFLICT'
  | 'TOO_MANY_REQUESTS'
  | 'INTERNAL_SERVER_ERROR'
  | 'BAD_GATEWAY'
  | 'SERVICE_UNAVAILABLE'
  | 'UNKNOWN_ERROR'
  // Auth 에러
  | 'AUTH_UNAUTHORIZED'
  | 'AUTH_INVALID_TOKEN'
  | 'AUTH_KAKAO_API_ERROR'
  // Users 에러
  | 'USER_NOT_FOUND'
  // Team 에러
  | 'TEAM_NOT_FOUND'
  | 'TEAM_FORBIDDEN'
  | 'TEAM_TASK_NOT_FOUND'
  | 'TEAM_TASK_BAD_REQUEST'
  | 'TEAM_COMMENT_NOT_FOUND'
  | 'TEAM_COMMENT_FORBIDDEN'
  | 'TEAM_INVITE_NOT_FOUND'
  | 'TEAM_INVITE_EXPIRED'
  | 'TEAM_INVITE_FORBIDDEN'
  | 'TEAM_MEMBER_ALREADY_EXISTS'
  | 'TEAM_MEMBER_NOT_FOUND'
  | 'TEAM_ROLE_CHANGE_FORBIDDEN'
  | 'TEAM_INVALID_ROLE'
  | 'TEAM_SELF_ROLE_CHANGE'
  | 'TEAM_MEMBER_STATUS_CHANGE_FORBIDDEN'
  | 'TEAM_SELF_STATUS_CHANGE'
  | 'TEAM_MASTER_STATUS_CHANGE'
  | 'TEAM_DISCORD_WEBHOOK_INVALID'
  // File Share 에러
  | 'FILE_SHARE_UNAUTHORIZED'
  | 'FILE_SHARE_FORBIDDEN'
  | 'FILE_SHARE_FILE_NOT_FOUND'
  | 'FILE_SHARE_INVALID_FILE_TYPE'
  // Notification 에러
  | 'NOTIFICATION_TELEGRAM_CONFIG_ERROR'
  | 'NOTIFICATION_TELEGRAM_API_ERROR'
  | 'NOTIFICATION_TELEGRAM_LINK_INVALID'
  | 'NOTIFICATION_TELEGRAM_ALREADY_LINKED'
  | 'NOTIFICATION_TELEGRAM_UNLINK_ERROR'
  // WS 전용 코드 (WsException 객체 payload / ws-exception.filter fallback)
  | 'CHAT_NOT_JOINED'
  | 'WS_ERROR'
  | 'WS_UNKNOWN_ERROR';
